name: "Create a GitHub Release Based on Specific Labels on a Pull Request"
description: "GitHub Action for creating a Release"
author: "githubofkrishnadhas"
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  token:
    description: "GitHub access token"
    required: true
  pr_number:
    description: "Pull request triggered the workflow"
    required: true
    type: number
  draft:
    description: "The release is a full release or a draft release"
    type: boolean
    required: false
  prerelease:
    description: "Release is latest or pre-release"
    type: boolean
    required: false
  generate_release_notes:
    description: "Auto generate release notes"
    type: boolean
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.pr_number }}
    - ${{ inputs.draft }}
    - ${{ inputs.prerelease }}
    - ${{ inputs.generate_release_notes }}

